# Generated by Django 4.2.4 on 2023-08-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('education', models.CharField(default='', max_length=64)),
                ('occupation', models.CharField(default='', max_length=64)),
                ('city', models.CharField(default='', max_length=64)),
                ('country', models.CharField(default='', max_length=64)),
                ('user_id', models.CharField(default='', max_length=8, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
