# Generated by Django 4.2.4 on 2023-08-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail',
        ),
    ]
